export { default as Navbar } from '@/components/Navbar'
export { default as Hero } from '@/components/Hero'
export { default as About } from '@/components/About'
export { default as Projects } from '@/components/Projects'
export { default as WorkExperience } from '@/components/WorkExperience'
export { default as ProjectCard } from '@/components/ProjectCard'
export { default as ExperiencePoint } from '@/components/ExperiencePoint'

export { default as Button } from '@/components/shared/Button'
export { default as TypingEffect } from '@/components/shared/TypingEffect'
export { default as TitleText } from '@/components/shared/TitleText'
